# Comparison des différentes méthodes {#sec:comparison}

## Comparison with the FST approach

L'approche FST fournit un

The FST approach provides a useful tool to validate a method of construction of linear filter. 
Indeed, a linear filter can be considered as suboptimal if we can find a set of weight for the FST approach that gives better results (in terms of fidelity, smoothness and timeliness) with the same (or higher) polynomial constraints.

For $h=6$ (13-term symmetric filter), for the RKHS filters we find that:

- imposing that asymmetric filters preserve constants, the FST approach gives better results for all values of $q$ for the filters computed with $b_{q,G}$ and $b_{q,\gamma}$, and for $q\leq 3$ for the one computed with $b_{q,\varphi}$.

- imposing that asymmetric filters preserve linear trends, the FST approach gives better results for $q\in[2,5]$ for the filters computed with $b_{q,G}$ and $b_{q,\gamma}$, and for $q\in[2,4]$ for the one computed with $b_{q,\varphi}$.

`r fa_arrow_circle_right` Therefore, the RKHS approach seems not to be the better approach to build asymmetric filters to apply to monthly regular data (i.e.: data for which we usually use $h=6$).

For the local polynomial filters we find that:

- imposing that asymmetric filters preserve constants, the FST approach gives better results than the LC method for all values of $q$. 
Adding the timeliness criterion allows to have better results than the FST approach for $q=0,1$.

- imposing that asymmetric filters preserve linear trends, the FST approach gives better results for $q\in[2,5]$ for the LC and QL methods. 
Adding the timeliness criterion doesn't change the results.

`r fa_arrow_circle_right` In terms of quality criteria, local polynomial seems to perform better for real-time and one-period ahead filters ($q=0,1$).

Those comparisons can be seen in an online application available at https://aqlt.shinyapps.io/FSTfilters/.

## Illustration with an example

In this section we compare the different asymmetric filters applying them to the French industrial production index of manufacture of motor vehicles, trailers and semi-trailers^[This series is produced by the INSEE, the French National Statistical Office, and is available at https://bdm.insee.fr/series/sdmx/data/SERIES_BDM/010537940.]. 
For simplicity, for the FST approach we only show an extreme filter example minimizing the phase shift by putting a large weight to the timeliness ($\alpha = 0$, $\beta = 1$, $\gamma = 1000$). 
For local polynomial filters, the Henderson kernel is used with $R=3.5$.
The figure \@ref(fig:cl2all) shows the results around a turning point (the economic crisis of 2009) and during "normal cycles" (between 2000 and 2008), from $q=0$ (real-time estimates) to $q=3$ (three future available observations).

\begin{figure}[!ht]
\animategraphics[autoplay,loop,width=\textwidth,controls]{2}{img/illustration/illustration_}{1}{7}
\caption{Application of asymmetric filters to the French industrial production index of manufacture of motor vehicles, trailers and semi-trailers.}\label{fig:cl2all}\footnotesize
\emph{Note: The final trend is the one computed by a symmetric 13-terms Henderson filter}

\emph{To see the animation, the PDF must be open with Acrobat Reader, KDE Okular, PDF-XChange or Foxit Reader.
Otherwise you will only be able to see the results for the DAF filter.}
\end{figure}

```{r cl2all, echo = FALSE, fig.cap = "Application of asymmetric filters to the French industrial production index of manufacture of motor vehicles, trailers and semi-trailers.", eval = is_html, note = "The final trend is the one computed by a symmetric 13-terms Henderson filter."}
slickR::slickR(
    sprintf("img/illustration/illustration_%i.png",1:7),
    height = 500,
    width = '95%')
```
<p class="caption" id ="note">Note: The final trend is the one computed by a symmetric 13-terms Henderson filter.</p>

For this example, in terms of time lag to detect the turning point of February 2009^[
A turning point (upturn) is defined to occur at time $t$ if $y_{t-k}\geq\cdots\geq y_{t-1}<y_t\leq y_{t+1}\leq\cdots y_{t+m}$. 
A downturn would be equivalently defined as a date $t$ $y_{t-k}\leq\cdots\leq y_{t-1}>y_t\geq y_{t+1}\geq\cdots y_{t+m}$.
Following @Zellner1991, $k=3$ and $m=1$ are chosen given the smoothness of the trend-cycle data. 
], the DAF is the worst filter since it introduces a delay of one month until $q=3$. 
LC, QL, $b_{q,\gamma}$ filters introduce a delay only for real-time filter ($q=0$) of two months for QL filter and one month for the others.
Surprisingly, the FST filter that minimize the phase shift introduce a time lag for $q=0$ and $q=1$ (the upturn is detected earlier), whereas $b_{q,\phi}$ doesn't introduce any time lag.

:::: {.remarque data-latex=""}
Those results differ from the one obtained in the real-time during the economic crisis. 
Indeed, here we take the time series already seasonally adjusted in the overall period, whereas during the real-time estimates, the seasonal adjustment process also introduce a time lag.
::::


In terms of revision error, the DAF filters also give the worst results. 
For real-time estimates ($q=0$), the LC and RKHS filters minimize the revision between 2000 and 2008 but when more data are available all the methods (except the DAF filters) give similar results. 
As excepted, the QL filter minimizes the revision around the turning point of 2009 since it is the only filter that preserve polynomial trends of degree 1. 
For small values of $q$, $b_{q,\phi}$ filter distorts less polynomial trends of degree 1 and 2 than the other RKHS filters ($b_l$ and $b_q$ statistics are lower, table \@ref(tab:criteriarkhs)): it explains why it performs better around the turning point.

With this simple example we cannot generalize properties on the different asymmetric filters, but it gives some leads to extend this study:

- minimize the timeliness doesn't imply earlier detection of turning points: more investigations on the timeliness criterion could be done;

- accept some bias in polynomial trends preservation can lead to asymmetric filters that performs better in term of turning points detection;

- for almost all the filters, there is no time lag to detect the turning points when two future observations are available, and the different methods gives similar results. 
Therefore, it is pointless to optimize asymmetric filters when too much future observations are available.

Moreover, this example also illustrates that the different methods perform better than the DAF filters. 
The real-time estimates methods that use this filter could be easily improved.
This is for example the case of STL (Seasonal-Trend decomposition based on Loess) seasonal adjustment method proposed by @cleveland90.

\newpage
