# (APPENDIX) Annexe {-} 

\newpage
# Equiv FST


```{r thhendersonh6, fig.cap = "Ensemble des poids pour lesquels la méthode FST n'est pas équivalente aux moindres carrés pondérés pour $h=6$ (filtre symétrique de 12 termes) et sous contrainte de préservation des polynômes de degré au plus 2 ($d=0,1,2$).", cache = TRUE,fig.height=height_cube}
poids_non_equiv <- readRDS(sprintf("data/th_henderson/poids_non_equiv_h%i.RDS",6))

par(mfrow = c(1,3), 
    mar = 0 + c(1, 0, 1, 0),
    mai = c(0.2, 0.2, 0.2, 0.2))
for (p in 0:2){
    for(q in names(poids_non_equiv[[sprintf("p=%i",p)]])){
        titre <- sprintf("p = %i - %s", p, gsub("="," = ",q))
        data <- poids_non_equiv[[sprintf("p=%i",p)]][[q]]
        if(nrow(data)>0){
            scatter_3D(poids_non_equiv[[sprintf("p=%i",p)]][[q]],
                       theta = 150,
                       titre = titre)
        }
        
    }
}
```

```{r thhendersonh11d01, fig.cap = "Ensemble des poids pour lesquels la méthode FST n'est pas équivalente aux moindres carrés pondérés pour $h=11$  (filtre symétrique de 23 termes) et sous contrainte de préservation des polynômes de degré au plus 2 ($d=0,1,2$).", cache = TRUE,fig.height=height_cube*5}
poids_non_equiv <- readRDS(sprintf("data/th_henderson/poids_non_equiv_h%i.RDS",11))
par(mfrow = c(5,3), 
    mar = 0 + c(1, 0, 1, 0),
    mai = c(0.2, 0.2, 0.2, 0.2))
for (p in 0:2){
    for(q in names(poids_non_equiv[[sprintf("p=%i",p)]])){
        titre <- sprintf("p = %i - %s", p, q)
        data <- poids_non_equiv[[sprintf("p=%i",p)]][[q]]
        if(nrow(data)>0){
            scatter_3D(poids_non_equiv[[sprintf("p=%i",p)]][[q]],
                       theta = 150,
                       titre = titre)
        }
        
    }
}
```
